### ISSUE TITLE
Extra information needed besides README

### ISSUE THREAD

**Issue by Polaris0421** [Esmail-ibraheem/Dali#1]
hi, i'm trying to implement the latent diffusion, but I have some problem running the official codes and i find your code which seems easier for me to understand. Have you run your codes and get any results? Your readme is quite simple and I can't figure out how to run your code. Thanks

**Comment by Esmail-ibraheem** [comment]
It's an implementation of the ddpm paper, it is just an implementation of the gauasing diffusion operations, so you can run the gauasing diffusion.py file
